//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGRES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgresDataBaseEntities : DbContext
    {
        public static ProgresDataBaseEntities _context;
        public ProgresDataBaseEntities()
            : base("name=ProgresDataBaseEntities")
        {
        }

        public static ProgresDataBaseEntities GetContext()
        {
            if (_context == null) { _context = new ProgresDataBaseEntities(); }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Outfit> Outfit { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<OrderList> OrderList { get; set; }
    }
}
