//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGRES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Outfit = new HashSet<Outfit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OutfitID { get; set; }
        public int Outfit_Count { get; set; }
        public string Customer_Surname { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Midname { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Email { get; set; }
        public string Pay_Option { get; set; }
        public decimal TotalSum { get; set; }
        public bool IsDone { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Identificator { get; set; }
        public string Adress_Info { get; set; }
        public string Shopping_Info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfit { get; set; }
    }
}
